"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import { AppShell } from "@/components/app-shell";
import { Notice } from "@/components/notice";
import { FreightBooking, ProcurementJob, ProductionStage, procurementStatuses } from "@/lib/database.types";
import { configurationError, supabaseRequest } from "@/lib/supabase";

const statusColours: Record<string, string> = { "Awaiting Confirmation":"#8b9aa6", Confirmed:"#168cff", "In Production":"#f1870d", "Production Completed":"#7555e6", "Fully Dispatched":"#20af63" };
function formatDate(value:string|null){if(!value)return "—";return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(value.length===10?`${value}T00:00:00Z`:value));}
function percent(value:number,total:number){return total?`${(value/total*100).toFixed(1)}%`:"0%";}

export default function Home(){
  const [jobs,setJobs]=useState<ProcurementJob[]>([]),[stages,setStages]=useState<ProductionStage[]>([]),[bookings,setBookings]=useState<FreightBooking[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setMessage(null);try{const [j,s,b]=await Promise.all([
    supabaseRequest<ProcurementJob[]>("procurement_jobs?select=*,suppliers(id,name,active)&order=updated_at.desc"),
    supabaseRequest<ProductionStage[]>("production_stages?select=*,procurement_jobs(*,suppliers(id,name,active)),suppliers(id,name,active)&order=updated_at.desc"),
    supabaseRequest<FreightBooking[]>("freight_bookings?select=*,procurement_jobs(*,suppliers(id,name,active)),production_stages(*),suppliers(id,name,active),freight_references(*),freight_forwarders(*),origin:locations!freight_bookings_origin_location_id_fkey(*),destination:locations!freight_bookings_destination_location_id_fkey(*)&archived_at=is.null&order=updated_at.desc")
  ]);setJobs(j);setStages(s);setBookings(b);}catch(error){setMessage((error as Error).message);}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const statusCounts=useMemo(()=>procurementStatuses.map(status=>({status,count:jobs.filter(job=>job.status===status).length})),[jobs]);
  const stagesByJob=useMemo(()=>stages.reduce<Record<string,ProductionStage[]>>((map,stage)=>{(map[stage.procurement_job_id]||=[]).push(stage);return map;},{}),[stages]);
  const bookingsByJob=useMemo(()=>bookings.reduce<Record<string,FreightBooking[]>>((map,booking)=>{(map[booking.procurement_job_id]||=[]).push(booking);return map;},{}),[bookings]);
  const offTrack=bookings.filter(b=>b.risk==="Off Track").length,onTrack=bookings.filter(b=>b.risk==="On Track").length;
  const unplannedJobs=jobs.filter(job=>{const js=stagesByJob[job.id]||[];if(!js.length)return job.status!=="Awaiting Confirmation";return (bookingsByJob[job.id]||[]).reduce((n,b)=>n+b.container_quantity,0)<js.reduce((n,s)=>n+s.container_quantity,0);}).length;
  const totalContainers=jobs.reduce((n,j)=>n+(j.total_containers||0),0),maxStatus=Math.max(1,...statusCounts.map(x=>x.count));let cursor=0;
  const stops=statusCounts.map(x=>{const start=cursor;cursor+=jobs.length?x.count/jobs.length*100:0;return `${statusColours[x.status]} ${start}% ${cursor}%`;}).join(", ");
  const donutStyle={"--donut":jobs.length?`conic-gradient(${stops})`:"#263744"} as CSSProperties;
  return <AppShell>
    <header className="dashboard-head"><div><h1>Supply Chain Dashboard</h1><div className="tabs"><button className="selected">Overview</button><Link href="/procurement">Jobs</Link><Link href="/production">Production</Link><Link href="/freight">Freight</Link></div></div><div className="dashboard-actions"><span className="live-data-indicator"><i/> Live Supabase data</span><button onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"↻ Refresh"}</button></div></header>
    {message&&<Notice message={message}/>} {configurationError()&&!message&&<Notice message={configurationError()!}/>}
    <section className="dashboard-metrics">{[["Total Jobs",jobs.length,"Current procurement jobs","blue","▣"],["In Production",statusCounts.find(x=>x.status==="In Production")?.count||0,percent(statusCounts.find(x=>x.status==="In Production")?.count||0,jobs.length),"orange","◉"],["Freight On Track",onTrack,percent(onTrack,bookings.length),"green","✓"],["Freight Off Track",offTrack,percent(offTrack,bookings.length),"red","!"],["Not Planned",unplannedJobs,"Jobs with freight remaining","purple","○"],["Containers",totalContainers,"Across all jobs","neutral","▤"]].map(([label,value,detail,tone,icon])=><article className={`dashboard-metric ${tone}`} key={label}><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div><div className="metric-art"><b>{icon}</b></div></article>)}</section>
    <section className="visual-grid dashboard-live-grid"><article className="dash-panel status-panel"><h2>Procurement Job Status</h2><div className="donut-wrap"><div className="donut live-donut" style={donutStyle}><span><b>{jobs.length}</b><small>jobs</small></span></div><ul>{statusCounts.map(x=><li key={x.status}><i style={{background:statusColours[x.status]}}/>{x.status}<small>{x.count} ({percent(x.count,jobs.length)})</small></li>)}</ul></div></article>
    <article className="dash-panel stage-panel"><h2>Jobs by Current Status</h2><div className="bar-chart live-bars">{statusCounts.map(x=><div key={x.status}><span style={{height:`${Math.max(x.count?12:0,x.count/maxStatus*155)}px`,background:statusColours[x.status]}}><b>{x.count}</b></span><small>{x.status}</small></div>)}</div></article>
    <article className="dash-panel freight-risk-panel"><h2>Freight Risk &amp; Planning</h2><div className="freight-risk-summary"><div className="risk-total"><strong>{bookings.length}</strong><span>active bookings</span></div><div><span><i className="green-bg"/>On Track</span><strong>{onTrack}</strong><small>{percent(onTrack,bookings.length)}</small></div><div><span><i className="red-bg"/>Off Track</span><strong>{offTrack}</strong><small>{percent(offTrack,bookings.length)}</small></div><div><span><i className="purple-bg"/>Not Planned</span><strong>{unplannedJobs}</strong><small>jobs with containers remaining</small></div></div><Link className="panel-link" href="/freight">Open freight planning →</Link></article></section>
    <section className="dash-panel all-jobs"><div className="all-jobs-title"><div><h2>All Jobs</h2><p>{loading?"Loading current records…":`${jobs.length} current procurement job${jobs.length===1?"":"s"}`}</p></div><Link href="/procurement">Manage jobs →</Link></div><div className="table-wrap"><table><thead><tr><th>Job / Sales Order</th><th>Client</th><th>Supplier</th><th>Supplier PO</th><th>Project Manager</th><th>Required On-Site</th><th>Containers</th><th>Job Status</th><th>Production Stage</th><th>Timing</th><th>Freight Status</th><th>Freight Risk</th><th>Last Update</th></tr></thead><tbody>{loading?<tr><td colSpan={13} className="empty">Loading live job data…</td></tr>:jobs.length===0?<tr><td colSpan={13} className="empty"><strong>No procurement jobs found</strong><span>Add a job in Procurement to see it here.</span></td></tr>:jobs.map(job=>{const js=stagesByJob[job.id]||[],stage=js[0],bs=bookingsByJob[job.id]||[],booking=bs[0],planned=bs.reduce((n,b)=>n+b.container_quantity,0),staged=js.reduce((n,s)=>n+s.container_quantity,0);return <tr key={job.id}><td><strong>{job.sales_order_number||job.client_name}</strong></td><td>{job.client_name}</td><td>{job.suppliers?.name||"—"}</td><td>{job.supplier_po_number||"—"}</td><td>{job.project_manager||"—"}</td><td>{formatDate(job.required_onsite_date)}</td><td>{job.total_containers??"—"}</td><td><span className="stage dashboard-status">{job.status||"Not set"}</span></td><td>{stage?.stage_reference||"Not planned"}</td><td>{stage?.timing_status||"—"}</td><td>{booking?.status||(staged>planned?`Not Planned (${staged-planned})`:"—")}</td><td><span className={`risk ${booking?.risk==="Off Track"?"delayed":booking?"on-track":"not-planned"}`}>{booking?.risk||"Not Planned"}</span></td><td>{formatDate(job.updated_at)}</td></tr>;})}</tbody></table></div></section>
  </AppShell>;
}
